version: "2"
services:
  test:
    build: ./app
    command: ["./wait-for-it.sh", "zap:8090", "-t", "120", "--", "./test.sh"]
    volumes:
      - .:/usr/src/wrk
    depends_on:
      - "hub"
      - "zap"
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
    links:
      - hub
  zap:
    image: owasp/zap2docker-weekly
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true
    ports:
      - "8090:8090"
