version: "2"
services:
  test:
    build: ./app
    volumes:
      - .:/usr/src/wrk
    depends_on:
      - "hub"
      - "zap"
      - "nowasp"
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
    links:
      - hub
  zap:
    image: owasp/zap2docker-weekly
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -addonupdate -addoninstall pscanrulesAlpha -addoninstall pscanrulesBeta
    ports:
      - "8090:8090"
  nowasp:
    image: citizenstig/nowasp
